**Numpy** :

Numpy is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [ ]:
import numpy as np

#what is array? :an array is a structure for storing and retrieving data
#np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
#one dimentional array is like a list
a = np.array([1,2,3,4,5])


#two dimentional array is like a table
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

#three dimentional array is like a set of tables
c=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

#to access an element in an array we use the index
print(a[0])
print(b[0][0])
#for 2 dim the format is row, column
print(b[0,1])
print(c[0][0][0])
#for 3 dim the format is table, row, column
print(c[0,0,0])

#to slice an array we use the slice operator
print(a[0:2])
print(b[0:2])
print(c[0:2])





1
1
2
1
1
[1 2]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
#to get the dimension of an array
a.ndim

#to get the shape of an array:The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension
a.shape

#to get the size of an array: The size of an array is the total number of elements in the array
a.size

#to get the data type of an array:Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”
a.dtype




In [ ]:
#to create a zero array 
np.zeros((2,2))

#to create an array filled with 1
np.ones((2,2)) #array([[1., 1.],[1., 1.]])
#to create an empty array
np.empty((2,2)) 

#to create an array of a range
np.arange(10) #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(1,10,2) #array([1, 3, 5, 7, 9])

#to create an array with values that are spaced linearly
np.linspace(0,10,5) #array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#to create an array with random values
np.random.rand(2,2) #array([[0.12345678, 0.98765432],[0.54321678, 0.12345678]])

#to create an array with identity values
np.eye(3)

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

#to sort an array 
np.sort(arr) #array([1, 2, 3, 4, 5, 6, 7, 8])

#to get the indices of the sorted array
np.argsort(arr) #array([1, 0, 3, 2, 5, 4, 6, 7])

#to search for a value in an array :it returns the index of the value
np.searchsorted(arr, 5) #4

#to partition an array :it returns the array partitioned around the kth element
np.partition(arr, 3) #array([2, 1, 3, 5, 7, 4, 6, 8])



In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

#to add two arrays
np.add(a, b) #array([6, 8, 10, 12])

#to subtract two arrays
np.subtract(a, b) #array([-4, -4, -4, -4])

#to multiply two arrays
np.multiply(a, b) #array([5, 12, 21, 32])

#to divide two arrays
np.divide(a, b) #array([0.2, 0.33333333, 0.42857143, 0.5])


In [ ]:
arr=np.array([1, 2, 3, 2, 5, 6, 5, 8])
#to find the unique values in an array
np.unique(arr) #array([1, 2, 3, 5, 6, 8])

#to find the frequency of unique values in an array
np.unique(arr, return_counts=True) #(array([1, 2, 3, 5, 6, 8]), array([1, 2, 1, 2, 1, 1]))

#to reshape an array
arr.reshape(2, 4) #array([[1, 2, 3, 2], [5, 6, 5, 8]])


(array([1, 2, 3, 5, 6, 8]), array([1, 2, 1, 2, 1, 1]))

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
#to convert a 1D array into a 2D array
a2 = a[np.newaxis, :] #np.newaxis is used to add a new axis to the array => array([[1, 2, 3, 4, 5, 6]])

b = np.expand_dims(a, axis=1) #np.expand_dims is used to add a new axis to the array => array([[1], [2], [3], [4], [5], [6]])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# to extract elements with condition
a[a > 5] #array([6, 7, 8, 9, 10, 11, 12])

# to extract indices of elements with condition
b = np.nonzero(a < 5)




In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#to create a new array from a section
b = a[2:5] #array([3, 4, 5])

#to stack arrays vertically 
vstack = np.vstack((a, b)) #array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [3, 4, 5, 6, 7, 8, 9, 10]])

#to stack arrays horizontally
hstack = np.hstack((a, b)) #array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3, 4, 5, 6, 7, 8, 9, 10])

#to split arrays vertically
vsplit = np.vsplit(a, 2) #array([array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 10])])

#to split arrays horizontally
hsplit = np.hsplit(a, 2) #array([array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 10])])

#to transpose an array
transpose = np.transpose(vstack) #array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [3, 4, 5, 6, 7, 8, 9, 10]])

#to reverse an array
reverse = np.flip(a) #array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]) 



In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#to get the max value
max_value = np.max(a)

#to get the min value
min_value = np.min(a)

#to get the mean value
mean_value = np.mean(a)

#to get the standard deviation
std_value = np.std(a)

#to get the variance
var_value = np.var(a)

#to get the median
median_value = np.median(a)






In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

#to save array to a file
np.save('a.npy', a)

#to load array from a file
b = np.load('a.npy')
print(b)

#to save array to a text file
np.savetxt('a.csv', a)

#to load array from a text file
c = np.loadtxt('a.csv')
print(c)
